### ISSUE TITLE
make fails in process_vcf_linkGeneNames.cpp

### ISSUE THREAD

**Issue by richelbilderbeek** [millanek/evo#3]
Hi Milan,

When I try to make your code ...

```
make
```

... I get the following error:

```
[...]
g++ -std=c++11   -c -o process_vcf_linkGeneNames.o process_vcf_linkGeneNames.cpp
process_vcf_linkGeneNames.cpp: In function ‘int linkGNMain(int, char**)’:
process_vcf_linkGeneNames.cpp:271:17: error: ‘print_vector_stream’ was not declared in this scope
                 print_vector_stream(ensGene, std::cerr);
                 ^~~~~~~~~~~~~~~~~~~
process_vcf_linkGeneNames.cpp:271:17: note: suggested alternative: ‘print_vector’
                 print_vector_stream(ensGene, std::cerr);
                 ^~~~~~~~~~~~~~~~~~~
                 print_vector
make: *** [<builtin>: process_vcf_linkGeneNames.o] Error 1
```

I reproduced the bug in [this GCC Travis log](https://travis-ci.org/richelbilderbeek/evo/jobs/591990040#L733) and [this clang Travis log](https://travis-ci.org/richelbilderbeek/evo/jobs/591990041#L732).

I hope you can fix this :+1: 

If you want (and that would be awesome), you can add the Travis CI checking by accepting [this Pull request](https://github.com/millanek/evo/pull/2).

Note there is also a warning:

```
g++ -c -std=c++11 process_vcf_coding_sequences.cpp -o Build/process_vcf_coding_sequences.o 
In file included from process_vcf_coding_sequences.cpp:9:
process_vcf_coding_sequences.h: In function ‘double getExpectedNumberOfNonsynonymousSites(const string&)’:
process_vcf_coding_sequences.h:348:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
```

The reason you did not return is obvious, but I hope you will fix that warning as well, else all your users will take the time to verify the warning is indeed harmless.

**Comment by millanek** [comment]
Hi Richel

Thanks, I fixed the error now. Sorry it took long, 'evo' is really just a personal library of tools and not used broadly. Although I am glad if you found any of it useful ;-).

Milan

**Comment by richelbilderbeek** [comment]
@millanek awesome!

Will you also accept [my Pull Request](https://github.com/millanek/evo/pull/2) to prevent this from happening in the future?
